[build]
  publish = "site"

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
    X-Frame-Options = "DENY"
    Referrer-Policy = "same-origin"
    Cache-Control = "public, max-age=0, must-revalidate"
